import type { Spread, SpreadPosition } from '@tarot/contracts';

const position = (
  id: string,
  order: number,
  name: string,
  prompt: string,
  x: number,
  y: number,
  rotation = 0,
): SpreadPosition => ({ id, order, name, prompt, coordinate: { x, y, rotation } });

export const spreads: Spread[] = [
  {
    id: 'single-insight',
    name: '한 장의 통찰',
    description: '지금 가장 주목할 핵심을 한 장으로 선명하게 살펴봅니다.',
    cardCount: 1,
    durationMinutes: 2,
    suitableFor: ['짧고 분명한 질문', '오늘의 초점', '마음 점검'],
    unsuitableFor: ['복잡한 선택지 비교', '여러 사람의 관계 분석'],
    positions: [
      position('focus', 0, '지금의 초점', '지금 가장 주목해야 할 에너지는 무엇인가요?', 50, 50),
    ],
    sourceIds: ['waite-pictorial-key-1911', 'spread-editorial-v1'],
  },
  {
    id: 'past-present-future',
    name: '과거–현재–미래',
    description: '시간의 흐름 속에서 현재의 선택과 앞으로의 가능성을 읽습니다.',
    cardCount: 3,
    durationMinutes: 4,
    suitableFor: ['변화의 흐름', '관계의 진행', '진로의 방향'],
    unsuitableFor: ['예/아니오 단답', '확정된 미래 예언'],
    positions: [
      position('past', 0, '과거', '현재에 영향을 주는 지나온 흐름은 무엇인가요?', 18, 50),
      position('present', 1, '현재', '지금 마주하고 있는 핵심은 무엇인가요?', 50, 50),
      position(
        'future',
        2,
        '앞으로의 가능성',
        '현재의 흐름이 이어질 때 열리는 가능성은 무엇인가요?',
        82,
        50,
      ),
    ],
    sourceIds: ['spread-editorial-v1'],
  },
  {
    id: 'situation-obstacle-advice',
    name: '상황–장애물–조언',
    description: '문제의 본질과 걸림돌, 지금 취할 수 있는 태도를 함께 살펴봅니다.',
    cardCount: 3,
    durationMinutes: 4,
    suitableFor: ['막힌 문제', '실천 조언', '일반적인 고민'],
    unsuitableFor: ['두 선택지의 직접 비교'],
    positions: [
      position('situation', 0, '상황', '질문의 중심에 놓인 상황은 무엇인가요?', 18, 50),
      position('obstacle', 1, '장애물', '진행을 어렵게 만드는 요인은 무엇인가요?', 50, 50),
      position('advice', 2, '조언', '지금 도움이 되는 태도나 행동은 무엇인가요?', 82, 50),
    ],
    sourceIds: ['spread-editorial-v1'],
  },
  {
    id: 'two-paths',
    name: '두 선택지 비교',
    description: '두 방향이 품은 기회와 부담을 나란히 놓고 비교합니다.',
    cardCount: 5,
    durationMinutes: 7,
    suitableFor: ['두 선택지', '이직과 잔류', '관계의 방향'],
    unsuitableFor: ['선택지가 명확하지 않은 질문'],
    positions: [
      position('core', 0, '선택의 핵심', '이 선택에서 가장 중요한 기준은 무엇인가요?', 50, 50),
      position('path-a', 1, '첫 번째 길', '첫 번째 선택이 요구하는 태도는 무엇인가요?', 20, 30),
      position(
        'outcome-a',
        2,
        '첫 번째 길의 가능성',
        '첫 번째 선택이 열 수 있는 가능성은 무엇인가요?',
        20,
        72,
      ),
      position('path-b', 3, '두 번째 길', '두 번째 선택이 요구하는 태도는 무엇인가요?', 80, 30),
      position(
        'outcome-b',
        4,
        '두 번째 길의 가능성',
        '두 번째 선택이 열 수 있는 가능성은 무엇인가요?',
        80,
        72,
      ),
    ],
    sourceIds: ['spread-editorial-v1'],
  },
  {
    id: 'relationship-mirror',
    name: '관계의 거울',
    description: '나와 상대, 관계 사이에서 드러나는 강점과 긴장을 균형 있게 봅니다.',
    cardCount: 6,
    durationMinutes: 8,
    suitableFor: ['연애', '가족', '친구', '협업 관계'],
    unsuitableFor: ['타인의 속마음을 사실처럼 단정하는 질문'],
    positions: [
      position('self', 0, '나', '내가 이 관계에 가져오는 마음은 무엇인가요?', 20, 25),
      position('other', 1, '상대', '상대의 입장을 이해할 때 고려할 점은 무엇인가요?', 80, 25),
      position('dynamic', 2, '관계의 흐름', '두 사람 사이에 형성된 패턴은 무엇인가요?', 50, 38),
      position('strength', 3, '강점', '이 관계가 가진 건강한 자원은 무엇인가요?', 25, 75),
      position('friction', 4, '긴장', '오해나 마찰을 만드는 지점은 무엇인가요?', 75, 75),
      position('next-focus', 5, '다음 초점', '관계를 위해 지금 살펴볼 태도는 무엇인가요?', 50, 88),
    ],
    sourceIds: ['spread-editorial-v1'],
  },
  {
    id: 'celtic-cross',
    name: '켈틱 크로스',
    description: '복합적인 질문을 배경, 내면, 환경과 가능성까지 열 장으로 깊게 살펴봅니다.',
    cardCount: 10,
    durationMinutes: 15,
    suitableFor: ['복합적인 삶의 문제', '깊은 자기성찰', '장기적인 전환'],
    unsuitableFor: ['급한 단답', '집중하기 어려운 짧은 질문'],
    positions: [
      position('present', 0, '현재', '질문의 중심에 놓인 현재 에너지는 무엇인가요?', 36, 50),
      position('challenge', 1, '도전', '현재를 가로막거나 자극하는 힘은 무엇인가요?', 36, 50, 90),
      position('foundation', 2, '기반', '눈에 잘 보이지 않는 바탕은 무엇인가요?', 36, 82),
      position(
        'recent-past',
        3,
        '지나온 흐름',
        '멀어지고 있지만 여전히 영향을 주는 것은 무엇인가요?',
        12,
        50,
      ),
      position(
        'possibility',
        4,
        '의식과 가능성',
        '바라거나 의식하고 있는 가능성은 무엇인가요?',
        36,
        18,
      ),
      position(
        'near-future',
        5,
        '가까운 전개',
        '곧 마주할 수 있는 다음 국면은 무엇인가요?',
        60,
        50,
      ),
      position('self', 6, '나의 태도', '이 상황을 대하는 내 태도는 무엇인가요?', 88, 86),
      position('environment', 7, '환경', '주변 환경에서 고려할 힘은 무엇인가요?', 88, 64),
      position(
        'hopes-fears',
        8,
        '희망과 두려움',
        '기대와 걱정이 만나는 지점은 무엇인가요?',
        88,
        42,
      ),
      position(
        'outcome',
        9,
        '종합 가능성',
        '현재 흐름이 이어질 때 어떤 배움으로 모일 수 있나요?',
        88,
        20,
      ),
    ],
    sourceIds: ['waite-pictorial-key-1911', 'spread-editorial-v1'],
  },
];
